version: '3.8'
services:
  backend:
    image: todo-app-be
    container_name: todo-be
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${API_PORT}:8080
    networks:
      - todo-network
  db:
    image: postgres:alpine3.17
    container_name: todo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - todo-network
volumes:
  db-data:
networks:
  todo-network: